/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* src = "counter.v:1" *)
module counter(clk, rst, en, count);
  (* src = "counter.v:6" *)
  wire [3:0] _00_;
  (* src = "counter.v:10" *)
  wire [3:0] _01_;
  wire [3:0] _02_;
  (* src = "counter.v:10|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3" *)
  wire [3:0] _03_;
  (* src = "counter.v:3" *)
  input clk;
  (* src = "counter.v:4" *)
  output [3:0] count;
  (* src = "counter.v:3" *)
  input en;
  (* src = "counter.v:3" *)
  input rst;
  assign _02_[0] = en ? (* src = "counter.v:9" *) _01_[0] : count[0];
  assign _02_[1] = en ? (* src = "counter.v:9" *) _01_[1] : count[1];
  assign _02_[2] = en ? (* src = "counter.v:9" *) _01_[2] : count[2];
  assign _02_[3] = en ? (* src = "counter.v:9" *) _01_[3] : count[3];
  assign _00_[0] = rst ? (* src = "counter.v:7" *) 1'h0 : _02_[0];
  assign _00_[1] = rst ? (* src = "counter.v:7" *) 1'h0 : _02_[1];
  assign _00_[2] = rst ? (* src = "counter.v:7" *) 1'h0 : _02_[2];
  assign _00_[3] = rst ? (* src = "counter.v:7" *) 1'h0 : _02_[3];
  (* src = "counter.v:6" *)
  DFF _12_ (
    .C(clk),
    .D(_00_[0]),
    .Q(count[0])
  );
  (* src = "counter.v:6" *)
  DFF _13_ (
    .C(clk),
    .D(_00_[1]),
    .Q(count[1])
  );
  (* src = "counter.v:6" *)
  DFF _14_ (
    .C(clk),
    .D(_00_[2]),
    .Q(count[2])
  );
  (* src = "counter.v:6" *)
  DFF _15_ (
    .C(clk),
    .D(_00_[3]),
    .Q(count[3])
  );
  assign _03_[1] = count[1] &(* src = "counter.v:10|<techmap.v>:260|<techmap.v>:221" *)  count[0];
  assign _03_[2] = count[2] &(* src = "counter.v:10|<techmap.v>:260|<techmap.v>:229" *)  _03_[1];
  assign _01_[1] = count[1] ^(* src = "counter.v:10|<techmap.v>:263" *)  count[0];
  assign _01_[2] = count[2] ^(* src = "counter.v:10|<techmap.v>:263" *)  _03_[1];
  assign _01_[3] = count[3] ^(* src = "counter.v:10|<techmap.v>:263" *)  _03_[2];
  assign _01_[0] = count[0] ^(* src = "counter.v:10|<techmap.v>:262" *)  1'h1;
  assign _03_[0] = count[0];
endmodule
